// Code generated by "stringer -type=ChangeType -output=gen.go"; DO NOT EDIT.

package enum

import "strconv"

const _ChangeType_name = "UpsertJSONUpsertTextRemoveRenameApplyJSONPatchApplyTextPatch"

var _ChangeType_index = [...]uint8{0, 10, 20, 26, 32, 46, 60}

func (i ChangeType) String() string {
	i -= 1
	if i < 0 || i >= ChangeType(len(_ChangeType_index)-1) {
		return "ChangeType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ChangeType_name[_ChangeType_index[i]:_ChangeType_index[i+1]]
}
